language: python
sudo: false
os:
  - linux
python:
  - 3.6
  - 3.6-dev
before_install:
  - pip install -r requirements-dev.txt
script:
  - pytest
  - sphinx-build docs docs/_build
after_success:
  - codecov
